### PR TITLE
Making it better, faster, stronger

### PR DESCRIPTION
**Pull request by daemitus**
P. sure this solves scale flickering.

When using everyone-icons, xiv-combo replacements can start flickering. I think its due to too many nodes altered? So updated those to only change if the values are different.

I did have one CTD right near the end while I was writing this up, so it still needs some testing.  Cursed amounts of debug statements and such, but its a drastic improvement.

### CODE REVIEW

**Comment by daemitus** [comment]
@Haplo064 I've added pohky's battlechara work in, works great. 
AdjustIcon is required every setnameplate or the icon will flicker positions.
ScaleIcon is done conditionally, I think it helps with preventing XIVCombo actionbar slots from flickering.
I've left the cache in just to be safe, it may be safe to remove, but it barely hurts anything.

**Comment by daemitus** [comment]
Also, if all these sigs fail and you can't find them again, the explicit offsets are all available in clientstructs.

**Comment by daemitus** [comment]
We may need to add a 2nd groupManager check, there are 2 groupmanagers, iirc the 2nd is for stuff like eureka/bozja. Simple enough fix, just need to see if it fails in those  areas.

**Comment by daemitus** [comment]
Ive also fixed "Everyone Else Icons" so its actually everyone else and not everyone.

**Review by Haplo064 — APPROVED** [review]

**Comment by alexwh** [comment]
For what it's worth, I only installed this plugin recently and noticed xivcombo icons flickering long before, so it's probably an issue on their end.

**Pull request merged**
